### ISSUE TITLE
“networks_4_text_delta.py” is missing?

### ISSUE THREAD

**Issue by liulanyang-alpha** [Aria-Zhangjl/E3-FaceNet#1]
https://github.com/Aria-Zhangjl/E3-FaceNet/blob/8eeb62b75380b61a1a1928f9689f343b6908c1fe/sample.py#L113

**Comment by Aria-Zhangjl** [comment]
> https://github.com/Aria-Zhangjl/E3-FaceNet/blob/8eeb62b75380b61a1a1928f9689f343b6908c1fe/sample.py#L113

Hi, thank you for pointing out this bug. I realized that I made a mistake by not updating the name of the imported module when I uploaded the code. The correct import statement should be:
`
from training.networks_4_E3_Face import Generator 
`
I have also corrected the code in the sample.py file to reflect this change. Sorry for any inconvenience caused.
