### ISSUE TITLE
我想要你微信

### ISSUE THREAD

**Issue by luckyone-create** [Aria-Zhangjl/E3-FaceNet#10]
我是否能要到你的微信然后问一下关于复现这个代码的详细问题

**Comment by Aria-Zhangjl** [comment]
您好，有关代码的复现问题您可以在这个issue下用中文提问,如果有其他的问题可以联系我的邮箱：zhangjinlu@stu.xmu.edu.cn

**Comment by luckyone-create** [comment]
请问这句话中的model和spec可以用你源代码里就已经存在了的model和spec吗，还是要去哪里找？              Please check configuration files at conf/model and conf/spec。。   按照一步步复现了，我还是有好多报错

**Comment by Aria-Zhangjl** [comment]
可以直接使用源代码conf下的配置

**Comment by luckyone-create** [comment]
请问run_train_4_E3_Face.sh下的内容都要修改吗，我看里面的model名和conf下的model名不一样。

**Comment by Aria-Zhangjl** [comment]
是的，这个sh文件的model需要修改成conf下model的名称一致，即：
`export MODEL='model_E3_Face'`
其他的配置【例如DATADIR、OUTDIR等】则需要根据具体的文件路径进行修改。

**Comment by luckyone-create** [comment]
我向你发送了邮箱希望您能看一下
