### ISSUE TITLE
too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by 1911rdnfhsj** [Aria-Zhangjl/E3-FaceNet#11]
您好，我在测试您的代码时，运行“bash run_eval_4_E3_Face.sh”进行评估测试，报错信息为：
![Snipaste_2024-12-19_21-06-17](https://github.com/user-attachments/assets/8a46e916-6af8-4d0a-82f8-bcb8a9d5297f)
我定位错误位于metric_utils_delta.py的第348行：“text_embs,text_token_embs = opts.clip_model.encode_text(texts_ids)”。我在这一行代码前加入语句“print("encode_text return values:", opts.clip_model.encode_text(texts_ids))”后调试输出返回值为一个张量，而348行代码尝试解包它为两个值（text_embs 和 text_token_embs），这显然是不匹配的。请问您知道如何解决或您后期有修改过这个代码吗？期待您的回答，提前致谢！

**Comment by Aria-Zhangjl** [comment]
您好，这个地方是要使用clip提取句子的全局特征和局部的特征，需要对clip的源码进行修改，具体的修改方式详见readme中的tip，您也可以参考这个issue的回复: #6 .

**Comment by 1911rdnfhsj** [comment]
感谢您的回答，我之前将tip中的内容看错了，现已可以成功运行。

**Comment by Aria-Zhangjl** [comment]
好的 :relaxed:
