### ISSUE TITLE
bash train_train_4_E3_Face.sh

### ISSUE THREAD

**Issue by 1911rdnfhsj** [Aria-Zhangjl/E3-FaceNet#12]
您好，该行命令是否笔误，正确的命令是否应是：bash run_train_4_E3_Face.sh ？
![Snipaste_2024-12-20_15-31-06](https://github.com/user-attachments/assets/12f374aa-4e6e-47dd-9658-eb0318d19213)

**Comment by Aria-Zhangjl** [comment]
是的，我已修改更新readme文档
