### ISSUE TITLE
It seems that the released weight doesn't match the current code.

### ISSUE THREAD

**Issue by windlikestone** [Aria-Zhangjl/E3-FaceNet#3]
I also encountered "ModuleNotFoundError: No module named 'training.networks_4_text'" when loading the checkpoint.
It reports error in Line 91"network = legacy.load_network_pkl(f)".

**Comment by Aria-Zhangjl** [comment]
Hi, sorry for the delayed response. When doing the experiment, I used an informal name, 'networks_4_text', for the training script. However, when releasing the code, I renamed it to 'networks_4_E3_Face' to adhere to formal conventions. The saved model weights have stored the trained parameters along with the original code, including import statements. Consequently, an import error occurs when attempting to load the pretrained weights. I have rectified this issue, and the code should now function correctly.

Additionally, I have made a modification to the clip package. Specifically, I modified the model.py in the original clip script to enable simultaneous extraction of text features and token embeddings. To incorporate this change, please replace the existing model.py file in the clip installation path.

Sorry again for any inconvenience caused.

**Comment by windlikestone** [comment]
Thank you very much. (^w^)
