### ISSUE TITLE
  File "sample.py", line 107, in generate_images     gen_t_embds,gen_t_token = clip_model.encode_text(gen_t_ids) ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by daidai321** [Aria-Zhangjl/E3-FaceNet#6]
File "sample.py", line 107, in generate_images
    gen_t_embds,gen_t_token = clip_model.encode_text(gen_t_ids)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Aria-Zhangjl** [comment]
Hi, I have made a modification to the clip package. Specifically, I modified the model.py in the original clip script to enable simultaneous extraction of text features and token embeddings. To incorporate this change, please replace the existing [model.py](https://github.com/Aria-Zhangjl/E3-FaceNet/blob/main/model.py)  file in the clip installation path.
Sorry again for any inconvenience caused.

**Comment by daidai321** [comment]
Thank you so much, it's working perfectly!
